language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - TRAVIS=true bundle exec rspec spec/
gemfile:
  - gemfiles/Gemfile.rails-3.2.x.gemfile
  - gemfiles/Gemfile.rails-4.0.x.gemfile
  - gemfiles/Gemfile.rails-edge.gemfile
  - gemfiles/Gemfile.draper-1.0.x.gemfile
  - gemfiles/Gemfile.draper-1.1.x.gemfile
  - gemfiles/Gemfile.draper-1.2.x.gemfile
  - gemfiles/Gemfile.draper-1.3.x.gemfile
  - gemfiles/Gemfile.draper-edge.gemfile
notifications:
  email:
    on_failure: change
branches:
  only:
    - master

