language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - TRAVIS=true bundle exec rspec spec/
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-edge
  - gemfiles/Gemfile.draper-1.0.x
  - gemfiles/Gemfile.draper-1.2.x
  - gemfiles/Gemfile.draper-1.3.x
  - gemfiles/Gemfile.draper-edge
notifications:
  email:
    on_failure: change
branches:
  only:
    - master

